### ISSUE TITLE
Implementation limit exceeded Too many values (more than 1500)

### ISSUE THREAD

**Issue by riicardofarias** [LifeOrYou/cakephp-firebird-utility#2]
Hello,

When i use the hasMany association I will receive this error when the results exceed 1500 records.

`SQLSTATE[HY000]: General error: -901 Dynamic SQL Error SQL error code = -901 Implementation limit exceeded Too many values (more than 1500) in member list to match against`

Because the query contains `WHERE Pesagens.ANIMAL_ID in (:c0,:c1,:c2,:c3,:c4,:c5,:c6,:c7,:c8,:c9,:c10...`. I replaced "IN" to "SIMILAR TO" on SGDB and works fine, but i dont' know how do this in CakePHP.

**Comment by maratth** [comment]
Hi, 

You juste replace 'IN' word by 'SIMILAR TO' ?
I don't understand what to want to.

Can you give me more details ?

**Comment by riicardofarias** [comment]
Yes, an error ocurred because cakephp creates an subquery with IN condition.

The problem can be fixed replacing IN to `WHERE Pesagens.ANIMAL_ID SIMILAR TO ':c0|:c1|:c2'` or using `WHERE Pesagens.ANIMAL_ID = :c0 AND Pesagens.ANIMAL_ID =:c1 AND Pesagens.ANIMAL_ID =:c2` on cakephp. But i don't know how change the default query generator on cakephp.

**Comment by riicardofarias** [comment]
I accessed the `prepare `function on `Driver\Firebird.php` and debug $sql var.

The error occurred when cakephp generate this query `'SELECT  Pesagens.ID AS "Pesagens__ID", Pesagens.PESO AS "Pesagens__PESO", Pesagens.DATA_PESAGEM AS "Pesagens__DATA_PESAGEM", Pesagens.HORA_PESAGEM AS "Pesagens__HORA_PESAGEM", Pesagens.ANIMAL_ID AS "Pesagens__ANIMAL_ID", Pesagens.SESSAO_ID AS "Pesagens__SESSAO_ID" FROM PESAGENS Pesagens WHERE Pesagens.ANIMAL_ID in (:c0,:c1,:c2,:c3,:c4,:c5,:c6,:c7,:c8,:c9,:c10,:c11,:c12,:c13,:c14,:c15,:c16,:c17,:c18,:c19,:c20,:c21,:c22,:c23,:c24,:c25...`

Are more than six thousand parameters.

**Comment by maratth** [comment]
Hum, i know this limitation of firebird but i can't do anything on this because the were sql part is build in CakePhp core file. I can't override the comportement in this driver.

If you need a alternative, i should you insert result of this query in temporary table and on another query you can join on this temporary table.

**Comment by riicardofarias** [comment]
I understand,

how i can do this in CakePHP?

**Comment by maratth** [comment]
With this method you can't use contains classicly.

But you can adapt this script :
```
$beforeSql = 'INSERT INTO YOU_TMP_TABLE (%s) %s';
$fieldsMap = [
    'produit' => 'Produits.code'
];           
$query->select(array_values($fieldsMap))->distinct();
$sql = sprintf($beforeSql, implode(', ', array_keys($fieldsMap)), $query->sql());

$stmt = $connection->prepare($sql);
// Only if you have params
$query->valueBinder()->attachTo($stmt);
$stmt->execute();
```
